version: 2.1
orbs:
  node: circleci/node@5.0.2
  docker: circleci/docker@2.2.0

jobs:
  build_and_test:
    executor: node/default
    steps:
      - checkout
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - node/install-packages:
                pkg-manager: yarn
            - run:
                command: yarn build
                name: Build app
  run_tests:
    docker:
      - image: mcr.microsoft.com/playwright:v1.23.1-focal
    steps:
      - checkout
      - run: yarn i -D @playwright/test
      - run: npx playwright install
      - run: npx playwright install chrome
      - run:
          name: Run playwright test
          command: yarn test
  build_docker_image:
    executor: docker/docker
    steps:
      - checkout
      - when:
          condition:
            equal: [ develop, << pipeline.git.branch >> ]
          steps:
            - setup_remote_docker
            - checkout
            - docker/check
            - docker/build:
                image: housebankng/$CIRCLE_PROJECT_REPONAME
                tag: latest
            - docker/push:
                image: housebankng/$CIRCLE_PROJECT_REPONAME
                tag: latest
workflows:
  Build_and_run_unit_tests:
    jobs:
      - build_and_test
  Build_and_deploy_service_to_docker_hub:
    jobs:
      - build_docker_image
  Run_Playwright_Test:
    jobs:
      - run_tests